<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE params [
<!ELEMENT params (
loginForm,
dispatchForm,
dbUser,
dbPassword,
dUserName,
dPassword,
dcsvPath, 
dbName,
adminPassword,
readOnlyPassword)>
<!ELEMENT loginForm    (#PCDATA)>
<!ELEMENT dispatchForm (#PCDATA)>
<!ELEMENT dbUser    (#PCDATA)>
<!ELEMENT dbPassword   (#PCDATA)>
<!ELEMENT dUserName    (#PCDATA)>
<!ELEMENT dPassword    (#PCDATA)>
<!ELEMENT dcsvPath     (#PCDATA)>
<!ELEMENT dbName       (#PCDATA)>
<!ELEMENT adminPassword (#PCDATA)>
<!ELEMENT readOnlyPassword (#PCDATA)>
]>

<params>
	<loginForm>comTest.sessionVars.LoginForm</loginForm>
	<dispatchForm>comTest.sessionVars.DispatchForm</dispatchForm>
	<dbUser>testUser</dbUser>	
	<dbPassword>testPassword</dbPassword>
	<dUserName>ferSure</dUserName>
	<dPassword>ferSure</dPassword>
	<dcsvPath>c:\dumpCsv</dcsvPath>
	<dbName>testdb</dbName>
	<adminPassword>testAdminPassword</adminPassword>
	<readOnlyPassword>testReadOnlyPassword</readOnlyPassword>
</params>