<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE params [
<!ELEMENT params (
loginForm, dispatchForm, dbName, dbUser, dbPassword, dUserName, dPassword,
csvPath)>
<!ELEMENT loginForm (#PCDATA)>
<!ELEMENT dispatchForm (#PCDATA)>
<!ELEMENT dbName (#PCDATA)>
<!ELEMENT dbUser (#PCDATA)>
<!ELEMENT dbPassword (#PCDATA)>
<!ELEMENT dUserName (#PCDATA)>
<!ELEMENT dPassword (#PCDATA)>

<!ELEMENT csvPath (#PCDATA)>

]>
<params>
	<loginForm>com.parts.security.Login</loginForm>
	<dispatchForm>com.parts.security.Dispatch</dispatchForm>
	<dbName>dbName</dbName>
	<dbUser>dbUser</dbUser>
	<dbPassword>dbPassword</dbPassword>
	<dUserName>defaultUser</dUserName>
	<dPassword>defaultPassword</dPassword>
	<csvPath>c:\dumpCsv</csvPath>
</params>